name: Build Plugin
on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch to build'
        required: true
        type: string
      build_config:
        description: 'The build configuration to use'
        required: true
        type: string
    secrets: inherit

jobs:
  build_plugin:
    runs-on: windows-latest

    steps:
      # Checkout the specific branch of the triggering repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.trigger_code_repo }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.BOT_READ_REPOS_TOKEN }}
          submodules: recursive

      # todo: find csproj file and extract the version from it

      # Include the plugin's dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build the plugin
      - name: Build
        run: |
          $build_config = '${{ inputs.build_config }}'
          $target_name = '${{ env.trigger_target_name }}'
          $ver = '${{ inputs.version }}'
          dotnet build --configuration $build_config --no-restore $target_name -p:AssemblyVersion=$ver -p:Version=$ver -p:FileVersion=$ver

      # todo: add zipping and moving to $HOME/builds
