#file: noinspection UndefinedParamsPresent

name: Publish Plugin
on:
  workflow_call:
    inputs:
      build_type:
        description: 'main, or test'
        required: true
        type: string
      repo:
        description: 'The repository to trigger the build for'
        required: true
        type: string
      branch:
        description: 'The branch to build'
        required: true
        type: string
      repo_url:
        description: 'The URL of the repo.json file being made, for the last target repo'
        required: true
        type: string
    secrets:
      BOT_WRITE_REPOS_TOKEN:
        description: 'Fine-Grained PAT with Repository: Content: Read and Write, on AutoRepo-Web'
        required: true
      DISCORD_HOOK:
        description: 'Discord hook to JSP#autorepo-triggers'
        required: true

jobs:
  publish_plugin:
    runs-on: ubuntu-latest

    steps:
      # Setup folder to place builds into
      - name: Create Output Folder
        id: make_output_folder
        run: |
          dev_folder="${{ runner.temp }}/builds"
          mkdir -p "$dev_folder"
          echo "DalamudDevPlugins=$dev_folder" >> $GITHUB_ENV

      # Download the uploaded artifact
      - name: Download Plugin Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_type }}
          path: ${{ env.DalamudDevPlugins }}

      # Recursively list the contents of `DalamudDevPlugins`
      - name: Show Upload Content
        id: show_content
        run: |
          echo "Listing contents of the directory to be uploaded:"
          find "${{ env.DalamudDevPlugins }}" -type f

      # Setup node for github-upload-action
      - name: Setup node
        id: setup_node
        uses: actions/setup-node@v1

      # Upload the plugin contents
      - name: Upload to GitHub
        uses: LasyIsLazy/github-upload-action@v0.2.0
        with:
          access-token: ${{ secrets.BOT_WRITE_REPOS_TOKEN }}
          file-path: ${{ env.DalamudDevPlugins }}
          owner: Just-Some-Plugins
          repo: AutoRepo-Web
          branch-name: main
          commit-message: "Upload Plugin: ${{ inputs.repo }}:${{ inputs.branch }}"

      # Notify Discord
      - name: Notify Discord (JSP#autorepo-triggers)
        uses: tsickert/discord-webhook@v6.0.0
        with:
          wait: false
          webhook-url: ${{ secrets.DISCORD_HOOK }}
          #flags: 4 # Flags are broken in this project
          embed-color: 12041720
          embed-title: "Plugin Uploaded: ${{ inputs.repo }}:${{ inputs.branch }}"
          embed-url: "${{ inputs.repo_url }}"
          embed-description: "[Action Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          # todo: add a field for each target_repo
          # design with https://message.style/app/editor
