#file: noinspection UndefinedParamsPresent

name: Publish Plugin
on:
  workflow_call:
    inputs:
      build_type:
        description: 'main, or test'
        required: true
        type: string
      repo:
        description: 'The repository to trigger the build for'
        required: true
        type: string
      branch:
        description: 'The branch to build'
        required: true
        type: string
      repo_url:
        description: 'The URL of the repo.json file being made, for the last target repo'
        required: true
        type: string
    secrets:
      BOT_WRITE_REPOS_TOKEN:
        description: 'Fine-Grained PAT with Repository: Content: Read and Write, on AutoRepo-Web'
        required: true
      DISCORD_HOOK:
        description: 'Discord hook to JSP#autorepo-triggers'
        required: true
concurrency:
  group: publish_${{ inputs.build_type }}_${{ inputs.repo }}:${{ inputs.branch }}
  cancel-in-progress: true

jobs:
  publish_plugin:
    runs-on: ubuntu-latest

    steps:
      # Setup folder to place builds into
      - name: Create Output Folder
        id: make_output_folder
        run: |
          dev_folder="${{ runner.temp }}/builds"
          mkdir -p "$dev_folder"
          echo "DalamudDevPlugins=$dev_folder" >> $GITHUB_ENV

      # Checkout the AutoRepo-Web repository
      - name: Checkout AutoRepo-Web Repository
        uses: actions/checkout@v4
        with:
          repository: Just-Some-Plugins/AutoRepo-Web
          path: web
          token: ${{ secrets.BOT_WRITE_REPOS_TOKEN }}

      # Move AutoRepo-Web to the correct location
      - name: Move AutoRepo-Web
        run: |
          mv web/* ${{ env.DalamudDevPlugins }}
          cd ${{ env.DalamudDevPlugins }}

      # Download the uploaded artifact
      - name: Download Plugin Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_type }}
          path: ${{ env.DalamudDevPlugins }}

      # Recursively list the contents of `DalamudDevPlugins`
      - name: Show Upload Content
        id: show_content
        run: |
          echo "Listing contents of the directory to be uploaded:"
          find "${{ env.DalamudDevPlugins }}" -type f

      # Change directory to the plugin directory
      - name: Change directory
        id: change_dir
        run: |
          cd ${{ env.DalamudDevPlugins }}

      # Add all changes
      - name: Add changes
        id: add_changes
        run: |
          git init
          git add .

      # Commit changes
      - name: Commit changes
        id: commit_changes
        run: |
          git commit -m "Upload Plugin: ${{ inputs.repo }}:${{ inputs.branch }}" || echo "No changes to commit"

      # Push changes
      - name: Push changes
        id: push_changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.BOT_WRITE_REPOS_TOKEN }}@github.com/Just-Some-Plugins/AutoRepo-Web.git
          git push origin main

      # Notify Discord
      - name: Notify Discord (JSP#autorepo-triggers)
        uses: tsickert/discord-webhook@v7.0.0
        with:
          wait: false
          webhook-url: ${{ secrets.DISCORD_HOOK }}
          #flags: 4 # flags are still broken
          embed-color: 12041720
          embed-title: "Plugin Uploaded: ${{ inputs.repo }}:${{ inputs.branch }}"
          embed-url: "${{ inputs.repo_url }}"
          embed-description: "[Action Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          # todo: add a field for each target_repo
          # design with https://message.style/app/editor
