#file: noinspection UndefinedParamsPresent

name: Publish Plugin
on:
  workflow_call:
    inputs:
      build_type:
        description: 'main, or test'
        required: true
        type: string
      repo:
        description: 'The repository to trigger the build for'
        required: true
        type: string
      branch:
        description: 'The branch to build'
        required: true
        type: string
      repo_url:
        description: 'The URL of the repo.json file being made, for the last target repo'
        required: true
        type: string
      file_list:
        description: 'The list of files to upload'
        required: true
        type: string
    secrets:
      BOT_WRITE_REPOS_TOKEN:
        description: 'Fine-Grained PAT with Repository: Content: Read and Write, on AutoRepo-Web'
        required: true
      DISCORD_HOOK:
        description: 'Discord hook to JSP#autorepo-triggers'
        required: true

jobs:
  publish_plugin:
    runs-on: ubuntu-latest

    steps:
      # Set git to use the bot's credentials
      - name: Setup Git
        id: setup_git
        run: |
          git config --global user.name 'just-some-bot'
          git config --global user.email 'justsomeplugins@zbee.codes'

      # Setup folder and clone repository directly
      - name: Create Output Folder and Clone Repository
        id: setup_repo
        run: |
          cd ${{ runner.temp }}
          
          # Clone the repository directly into builds directory
          git clone https://x-access-token:${{ secrets.BOT_WRITE_REPOS_TOKEN }}@github.com/Just-Some-Plugins/AutoRepo-Web.git builds
          
          # Set environment variable for future steps
          echo "DalamudDevPlugins=${{ runner.temp }}/builds" >> $GITHUB_ENV
           
      # Download the uploaded artifact
      - name: Download Plugin Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build_type }}
          path: ${{ env.DalamudDevPlugins }}

      # Recursively list the contents of `DalamudDevPlugins`
      - name: Show Upload Content
        id: show_content
        run: |
          echo "Listing contents of the directory to be uploaded:"
          find "${{ env.DalamudDevPlugins }}" -type f -printf "%p - Last Modified: %TY-%Tm-%Td %TH:%TM:%TS\n"

      # Add all changed files
      - name: Add Changes
        id: add_changes
        run: |
          for file in $(cat file_list.txt); do
            echo "File: $file"
          done

      # Commit changes
      - name: Commit changes
        id: commit_changes
        run: |
          cd ${{ env.DalamudDevPlugins }}
          git commit -m "Upload Plugin: ${{ inputs.repo }}:${{ inputs.branch }}" || echo "No changes to commit"

      # Push changes
      - name: Push changes
        id: push_changes
        run: |
          cd ${{ env.DalamudDevPlugins }}
          git push origin main

      # Notify Discord
      - name: Notify Discord (JSP#autorepo-triggers)
        uses: tsickert/discord-webhook@v7.0.0
        with:
          wait: false
          webhook-url: ${{ secrets.DISCORD_HOOK }}
          #flags: 4 # flags are still broken
          embed-color: 12041720
          embed-title: "Plugin Uploaded: ${{ inputs.repo }}:${{ inputs.branch }}"
          embed-url: "${{ inputs.repo_url }}"
          embed-description: "[Action Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          # todo: add a field for each target_repo
          # design with https://message.style/app/editor
